### ISSUE TITLE
shuffle=True

### ISSUE THREAD

**Issue by impulsecorp** [zhengxiawu/rethinking_performance_estimation_in_NAS#17]
Today you updated line 73 of augment.py from shuffle=False to shuffle=True.  I am curious as to why did you decided to make that change.

**Comment by zhengxiawu** [comment]
We always use shuffle=True in our experiment. However, some typos happened when we upload our code. shuffle=False may lead to worse performance. For example, in the Evolution algorithm, it only achieves 96.5. We debug the code for a long time and find that the issue is in the shuffle, after we set shuffle=True, it has exactly the same 97.3+ top-1 accuracy as we reported in our paper.
