### ISSUE TITLE
comparision with proxylessnas

### ISSUE THREAD

**Issue by liwei46** [zhengxiawu/rethinking_performance_estimation_in_NAS#4]
https://github.com/mit-han-lab/proxylessnas

Hello,

Thanks for sharing. I did not have time to understand all your code yet. But I am wondering have you do a comparison with  proxylessnas?  (link above)

Regards,
liwei

**Comment by zhengxiawu** [comment]
We do not compare our method with proxylessNAS, since
1. The architecture space is different, in [https://github.com/mit-han-lab/proxylessnas](proxylessnas) they only release a chain structure search space and method on imagenet. However, the search space used in our method is cell-based.
2. the BPE we found is on cifar10 dataset, if you want directly search on Imagenet, you may need some finetuning of the BPE-1 and BPE-2
3. Even with a small dataset (cifar10), founding optimal BPE had spent about 200+ GPU/days, which means that it is now infeasible on ImageNet. However, we also have an experiment about transfer learning (search on CIFAR-10 transferring to Imagenet), which shows comparable performance with much less searching cost.

**Comment by liwei46** [comment]
hi @zhengxiawu 

Great! Thanks for the reply. 

Regards,

**Comment by zhengxiawu** [comment]
hi, @liwei46  architectures in cell-based search space are 2 * 8^{14}, in proxyless NAS is about 6^{20}

**Comment by liwei46** [comment]
Thanks.
