### ISSUE TITLE
question about BPE with different Dataset

### ISSUE THREAD

**Issue by LiuTingWed** [zhengxiawu/rethinking_performance_estimation_in_NAS#7]
great job!

I have some questions about BPE1 and BPE2
I wanna implement this method to other datasets, How can I get the best BPE of the datasets
In your paper, the BPE is come from  MIP, Is it part of your code? I can see the result of BPE just print out in file, sorry, I am not figure out totally  

any suggestion thanks

**Comment by zhengxiawu** [comment]
Honestly, I don't suggest searching BPE for yourself. The BPE-1 and BPE-2 were found on a small dataset CIFAR-10, which still needs thousands of GPU hours. If you really want to find BPE on other datasets, here is my recommendation:
1) if the datasets have similar input size with cifar-10 (32), just finetune import hyperparameter ( layers and training epochs in Fig. 4) for new datasets.
2) Otherwise, you also need to finetune input image size, since we also found that input image size is important in ImageNet.

**Comment by LiuTingWed** [comment]
thanks a lot, bro.
I realize what I consult is hyper-parameters optimization problem. but, unfortunately, the datasets I mentioned are not small, I need read more papers. 
appreciate again :-)

**Comment by zhengxiawu** [comment]
you are welcome.
